# Generated by Django 3.2.25 on 2025-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='team_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
