# Generated by Django 3.2.25 on 2025-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('player', 'Player')], default='admin', max_length=10),
        ),
    ]
