# Generated by Django 4.2.21 on 2025-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_coachprofile_address_coachprofile_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Actif'), ('Inactive', 'Inactif'), ('Injured', 'Blessé')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='subgroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(choices=[('Midfielder', 'Milieu'), ('Defender', 'Défenseur'), ('Forward', 'Attaquant'), ('Goalkeeper', 'Gardien')], max_length=20),
        ),
    ]
