# Generated by Django 4.2.21 on 2025-07-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_playerprofile_category_playerprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='date_of_birth',
        ),
    ]
