# Generated by Django 4.2.21 on 2026-02-11 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_playerprofile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='accounts.group'),
        ),
    ]
