# Generated by Django 4.2.21 on 2026-02-13 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_playerprofile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Actif'), ('Inactive', 'Inactif'), ('Injured', 'Blessé')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='subgroup',
            index=models.Index(fields=['group', 'name'], name='accounts_su_group_i_29f7e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='subgroup',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_subgroup_per_group'),
        ),
    ]
