# Generated by Django 4.2.21 on 2026-03-13 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_group_name_alter_playerprofile_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('colors', models.CharField(blank=True, max_length=100, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academy/logos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('home_kit', models.ImageField(blank=True, null=True, upload_to='academy/kits/')),
                ('away_kit', models.ImageField(blank=True, null=True, upload_to='academy/kits/')),
                ('technical_director', models.CharField(blank=True, max_length=100, null=True)),
                ('head_coach_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_coach', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_staff', models.CharField(blank=True, max_length=100, null=True)),
                ('stadium_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stadium_location', models.CharField(blank=True, max_length=100, null=True)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_cafeteria', models.BooleanField(default=False)),
                ('has_dormitory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.academy'),
        ),
        migrations.AddField(
            model_name='group',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.academy'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='accounts.academy'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'academy')},
        ),
    ]
