# Generated by Django 4.2.21 on 2026-03-16 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_academy_alter_group_name_customuser_academy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Match Friendly', 'Match Friendly'), ('Tournament', 'Tournament')], default='Match Friendly', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('target_academy', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.academy')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.group')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.subgroup')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounts.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='accounts.playerprofile')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
    ]
