# Generated by Django 4.2.21 on 2026-04-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('technical_scores', models.JSONField(blank=True, default=dict)),
                ('technical_avg', models.FloatField(default=0)),
                ('tactical_scores', models.JSONField(blank=True, default=dict)),
                ('tactical_avg', models.FloatField(default=0)),
                ('physical_scores', models.JSONField(blank=True, default=dict)),
                ('physical_avg', models.FloatField(default=0)),
                ('mental_scores', models.JSONField(blank=True, default=dict)),
                ('mental_avg', models.FloatField(default=0)),
                ('fatigue_level', models.IntegerField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('pain_location', models.CharField(blank=True, max_length=100)),
                ('is_injured', models.BooleanField(default=False)),
                ('injury_details', models.TextField(blank=True)),
                ('medical_cert_valid', models.BooleanField(default=True)),
                ('school_grade_avg', models.FloatField(blank=True, null=True)),
                ('school_attendance', models.FloatField(blank=True, null=True)),
                ('school_behaviour', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.FloatField(default=0)),
                ('strength', models.TextField()),
                ('to_improve', models.TextField()),
                ('objective', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('attendance_present', models.IntegerField(default=0)),
                ('attendance_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.academy')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.coachprofile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.playerprofile')),
            ],
            options={
                'ordering': ['-month', '-created_at'],
                'unique_together': {('player', 'month')},
            },
        ),
    ]
