# Generated by Django 4.2.21 on 2026-04-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0018_playerreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('tactical', 'Tactical'), ('physical', 'Physical'), ('mental', 'Mental'), ('match_prep', 'Match Prep'), ('recovery', 'Recovery')], default='technical', max_length=20)),
                ('level', models.CharField(choices=[('A', 'A — Beginner'), ('B', 'B — Intermediate'), ('C', 'C — Advanced'), ('D', 'D — Elite')], default='B', max_length=1)),
                ('location', models.CharField(blank=True, default='Main Field', max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exercises', models.JSONField(blank=True, default=list)),
                ('recurrence', models.CharField(choices=[('none', 'No recurrence'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('recurrence_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='accounts.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='accounts.coachprofile')),
                ('groups', models.ManyToManyField(blank=True, related_name='training_sessions', to='accounts.group')),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='accounts.trainingsession')),
                ('subgroups', models.ManyToManyField(blank=True, related_name='training_sessions', to='accounts.subgroup')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
