# Generated by Django 4.2.21 on 2026-04-12 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0019_trainingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('tactical', 'Tactical'), ('physical', 'Physical'), ('mental', 'Mental'), ('match_prep', 'Match Prep'), ('recovery', 'Recovery')], default='technical', max_length=20)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('duration', models.IntegerField(default=15, help_text='Duration in minutes')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('instructions', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='accounts.academy')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
