# Generated by Django 4.2.21 on 2026-04-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_exercisetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photos/'),
        ),
    ]
