# Generated by Django 4.2.21 on 2026-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0021_coachprofile_bio_coachprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
    ]
