# Generated by Django 4.2.21 on 2026-04-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_playerprofile_bio_playerprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subgroups', to='accounts.coachprofile'),
        ),
    ]
