# Generated by Django 4.2.21 on 2026-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_subgroup_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username', 'academy')},
        ),
    ]
