# Generated by Django 4.2.21 on 2026-04-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0024_alter_customuser_options_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('Midfielder', 'Milieu'), ('Defender', 'Défenseur'), ('Forward', 'Attaquant'), ('Goalkeeper', 'Gardien')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
