# Generated by Django 4.2.21 on 2026-04-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0025_alter_playerprofile_group_alter_playerprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='border_radius_style',
            field=models.CharField(choices=[('Sharp', 'Sharp'), ('Rounded', 'Rounded'), ('Extra Rounded', 'Extra Rounded')], default='Rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='academy',
            name='color_3',
            field=models.CharField(default='#00d0cb', max_length=7),
        ),
        migrations.AddField(
            model_name='academy',
            name='color_4',
            field=models.CharField(default='#180033', max_length=7),
        ),
        migrations.AddField(
            model_name='academy',
            name='gradient_angle',
            field=models.IntegerField(default=135),
        ),
        migrations.AddField(
            model_name='academy',
            name='primary_color',
            field=models.CharField(default='#902bd1', max_length=7),
        ),
        migrations.AddField(
            model_name='academy',
            name='secondary_color',
            field=models.CharField(default='#4fb0ff', max_length=7),
        ),
    ]
