# Generated by Django 4.2.21 on 2026-04-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0026_academy_border_radius_style_academy_color_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='color_3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academy',
            name='color_4_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academy',
            name='header_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='academy',
            name='secondary_color_active',
            field=models.BooleanField(default=True),
        ),
    ]
