# Generated by Django 4.2.21 on 2026-04-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0027_academy_color_3_active_academy_color_4_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this coach can access.', related_name='assigned_coaches', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='assigned_subgroups',
            field=models.ManyToManyField(blank=True, help_text='Specific subgroups this coach can access.', related_name='assigned_coaches', to='accounts.subgroup'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='full_access_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups where this coach has access to ALL subgroups.', related_name='full_access_coaches', to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='accounts.coachprofile'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subgroups_legacy', to='accounts.coachprofile'),
        ),
    ]
