# Generated by Django 4.2.21 on 2026-04-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0028_coachprofile_assigned_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='coach',
        ),
    ]
