# Generated by Django 4.2.21 on 2026-04-23 03:05

from django.db import migrations, models


def convert_category_to_json_array(apps, schema_editor):
    """Convert existing plain string category values to JSON arrays before
    the column type changes to JSONField. E.g. 'technical' → '["technical"]'."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE accounts_trainingsession
            SET category = '["' || category || '"]'
            WHERE category IS NOT NULL
              AND category <> ''
              AND category NOT LIKE '[%'
        """)
        cursor.execute("""
            UPDATE accounts_trainingsession
            SET category = '[]'
            WHERE category IS NULL OR category = ''
        """)


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0029_remove_group_coach_remove_subgroup_coach'),
    ]

    operations = [
        migrations.RunPython(convert_category_to_json_array, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trainingsession',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
