# Generated by Django 4.2.21 on 2026-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0030_alter_trainingsession_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='subgroups',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.subgroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_coaches',
            field=models.ManyToManyField(blank=True, help_text='Specifically targeted coaches.', related_name='targeted_events', to='accounts.coachprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_players',
            field=models.ManyToManyField(blank=True, help_text='Specifically targeted players.', related_name='targeted_events', to='accounts.playerprofile'),
        ),
    ]
