# Generated by Django 4.2.21 on 2026-04-26 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0031_remove_event_group_remove_event_subgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Match Friendly', 'Match Friendly'), ('Tournament', 'Tournament'), ('Meeting', 'Meeting')], default='Match Friendly', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('event_id', models.CharField(blank=True, max_length=50, null=True)),
                ('event_type', models.CharField(choices=[('session', 'Training Session'), ('event', 'Agenda Event')], default='session', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
