# Generated by Django 4.2.21 on 2026-05-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('accounts', '0032_alter_event_type_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='colors',
        ),
    ]
