# Generated by Django 4.2.21 on 2026-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_playerattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
