# Generated by Django 4.2.21 on 2026-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_coachprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='phones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
