# Generated by Django 4.2.21 on 2026-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_coachprofile_phones_playerprofile_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('Midfielder', 'Milieu'), ('Defender', 'Défenseur'), ('Forward', 'Attaquant'), ('Goalkeeper', 'Gardien'), ('Indisponible', 'Indisponible')], max_length=20, null=True),
        ),
    ]
