# Generated by Django 4.2.21 on 2026-07-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_playerprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
