# Generated by Django 4.2.21 on 2026-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_playerprofile_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='biometric_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_biometric_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
