# Generated by Django 4.2.21 on 2026-09-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_playerprofile_biometric_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_notes', to='accounts.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to='accounts.coachprofile')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_notes', to='accounts.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
