# Generated by Django 4.2.21 on 2026-09-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_coachnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('Left', 'Gauche'), ('Right', 'Droit'), ('Both', 'Ambidextre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='playerreport',
            name='coach_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerreport',
            name='general_condition',
            field=models.CharField(blank=True, choices=[('good', 'Bonne'), ('average', 'Moyenne'), ('watch', 'À surveiller')], max_length=10),
        ),
        migrations.AddField(
            model_name='playerreport',
            name='objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerreport',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'En attente de validation'), ('approved', 'Validé')], default='approved', max_length=20),
        ),
    ]
