# Generated by Django 4.2.21 on 2026-09-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_playerprofile_preferred_foot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreport',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='strength',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='to_improve',
            field=models.TextField(blank=True),
        ),
    ]
