# Generated by Django 4.2.21 on 2026-09-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_playerreport_objective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='preferred_foot',
        ),
    ]
